name: Node.js CI

on:
  push:
    branches:
      - master

jobs:

  test-node:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x ]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run bootstrap
      - run: npm run build-all
      - run: npm run test-node


  test-browser:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        module: [ 'esm', 'umd' ]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run bootstrap
      - run: npm run build-all
      - run: npm run test-browser-${{ matrix.module }}


  coverage:

    name: Coverage

    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run bootstrap
      - run: npm run build-all
      - run: npm run test-coverage
